wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.16
    start_time: 1675326984.917216
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.8.16
      5: 0.13.9
      8:
      - 2
      - 3
      - 5
